github: [DominikOpalko, UltraSecTeam]
patreon: UltraSecPatreon
ko_fi: dominik-opalko
buy_me_a_coffee: dominik-opalko
open_collective: UltraSecCollective
custom: ["https://ultrasecuritymonitor.com/donate", "https://paypal.me/dominikopalko"]
